CREATE TABLE POSTS (
   post_id BIGINT AUTO_INCREMENT PRIMARY KEY,
   title VARCHAR(255) NOT NULL,
   content TEXT,
   hits BIGINT DEFAULT 0,
   author VARCHAR(255),
   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);