apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
  namespace: {{ $.Values.global.namespace }}
spec:
  replicas: {{ $.Values.global.replicas }}
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      containers:
        - name: gateway-service
          image: {{ .Values.image }}
          ports:
            - containerPort: {{ .Values.port }}
          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: {{ .Values.eureka.serviceUrl }}
            - name: SPRING_PROFILES_ACTIVE
              value: production
