spring:
  datasource:
    url: jdbc:h2:file:/nfs/k8s/h2-data/blog/blog-service-db;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

