spring.application.name: gateway-service
spring.profiles.active: prod

spring.cloud.gateway:
  discovery:
    locator:
      enabled: true  # Eureka로 등록된 서비스에 대해 동적으로 라우팅
  routes:
    - id: blog-route
      uri: lb://blog-service
      predicates:
        - Path=/blog/**
        - Method=GET
      filters:
        - StripPrefix=1

  global-cors:
    cors-configurations:
      '[/**]':
        allowed-origins:
          - "http://localhost:9000"
        allowed-methods:
          - POST
          - GET
          - OPTIONS
        allowed-headers:
          - "*"
        allow-credentials: true
  default-filters:
    - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials

eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8000/eureka/
    register-with-eureka: true
    fetch-registry: true
    rest-template-timeout:
      connect-timeout: 5000
      connect-request-timeout: 8000
      socket-timeout: 10000

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.netty: DEBUG

