spring.application.name: gateway-service

spring.cloud.gateway:
  discovery:
    locator:
      enabled: true  # Eureka로 등록된 서비스에 대해 동적으로 라우팅
  routes:
    - id: blog-service
      uri: lb://blog-service
      predicates:
        - Path=/blog/**
        - Method=GET
      filters:
        - StripPrefix=1
  globalcors:
    cors-configurations:
      '[/**]':
        allowedOrigins: "http://localhost:9000"

eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka/
    register-with-eureka: true
    fetch-registry: true