apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-service
  namespace: {{ $.Values.global.namespace }}
spec:
  replicas: {{ $.Values.global.replicas }}
  selector:
    matchLabels:
      app: eureka-service
  template:
    metadata:
      labels:
        app: eureka-service
    spec:
      containers:
        - name: eureka-service
          image: {{ .Values.image }}
          ports:
            - containerPort: {{ .Values.port }}