server.port: 8000
spring.application.name: eureka-service
spring.profiles.active: prod

eureka:
  instance:
    hostname: eureka-service
    registry:
      default-open-for-traffic-count: 1
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    region: default

  server:
    enable-self-preservation: true
    renewal-percent-threshold: 0.85